spring:
  application:
    name: yosefdreams
  datasource:
    url: jdbc:mysql://localhost:3306/yosef?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: build/schema.sql
            create-source: metadata
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
          rset: true

server:
  port: 8081
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        security: DEBUG
        mail: DEBUG
    root: INFO

app:
  jwt:
    secret: your-secret-key-here
    expiration: 604800000 # 7 days in milliseconds
  email:
    from: your-email@example.com
    reset-password:
      subject: Password Reset Request
  frontend:
    reset-password-url: http://localhost:3000/reset-password
